### PR TITLE
Request to start 2013-12-30-0 to 2014-01-16-0

### PR DESCRIPTION
**Pull request by kdraeder**
The modelio.nml files in this commit list are redundant
in CaseDocs and BuildConf/cplconf.  In addition, they
were created by the last cycle of the previous job,
and will be overwritten by the first cycle of the next job.
So they have almost no useful information to review.
Should I add one or both sets to the .gitignore file
to clarify what people should pay attention to?
Or I could add just the *0080 andor *0001 files to the commit
if anyone is worried about documenting everything that changes.

Someone should look at
/glade/scratch/raeder/f.e21.FHIST_BGC.f09_025.CAM6assim.011/run,
where I've reset the case to start from 2013-12-30-00000.
That did not require visible changes to the files in $CASEROOT,
so git will not bring them to your attention.

If you're feeling obsessive you can check the math
about the number of cycles specified, compared to the
intended run dates.  The cycles are the definitive number,
but it's good to be consistent between plans and intentions.

In these early approvals, it would be helpful to know what
you looked at.

### CODE REVIEW

**Comment by kdraeder** [comment]
Make that 'plans and implementation'

**Comment by kdraeder** [comment]
Recent queues and yesterday's discussion outweighed my intention to wait
for approval before submitting the job.  There were enough idle nodes that
it went into economy immediately.  So you won't be able to see how the 
the run directory was set up.

**Comment by jlsucar** [comment]
Hi Kevin,

I think it is very reasonable to skip approval this time to take advantage
of the queue situation. We will need to come up with a system to ensure
timely approval of the changes. That will probably mean a rotating list of
people being "on call" with some way for you to notify them when you need
an approval.

We will need to work on this while the machine is down. For example, I
can't see all of the files you changed because GitHub thinks the number of
files is too large and it gave up. See the attached screenshot. All I can
see from the website are the 80 copies of the same namelist, which is not
helpful. Perhaps we could remove the nml versions 2-80 from source control
to cut down on the number of files that changed. Or perhaps someone will
need to bring your changes down locally to look at them if GitHub just
can't be bothered to show all the files.

We'll need to put together some training of what to look for everyone who
will be "on call."

Anyways, for now please continue issuing these requests but let's iron out
the details next week.

Best wishes,

Jeff

**Comment by timhoar** [comment]
Yup ... taking advantage of the queue and the fact that we had just been
through the restart seems appropriate.
I agree that there are a lot of redundant namelist files under version
control. We should definitely sort this out, but it doesn't need to be done
before the machine goes down.

I see that you have advanced through the year boundary ... great.




Tim Hoar
Data Assimilation Research Section
National Center for Atmospheric Research
thoar@ucar.edu
303.497.1708

**Pull request merged**
